"""URL routes for the importer wizard."""

from django.urls import path

from . import (
    billing_views,
    column_mapping_views,
    connection_views,
    journey_views,
    query_views,
    settings_views,
    workflow_views,
)

app_name = "importer"

urlpatterns = [
    path("", workflow_views.landing, name="landing"),
    path(
        "column-mapping/",
        column_mapping_views.column_mapping_start,
        name="column_mapping_start",
    ),
    path("crm/connections/", connection_views.crm_connections, name="crm_connections"),
    path("crm/setup/", connection_views.crm_setup_start, name="crm_setup_start"),
    path("crm/setup/pick/", connection_views.crm_setup_pick, name="crm_setup_pick"),
    path(
        "crm/setup/choose/",
        connection_views.crm_setup_choose,
        name="crm_setup_choose",
    ),
    path(
        "crm/setup/practice/",
        connection_views.crm_setup_practice,
        name="crm_setup_practice",
    ),
    path(
        "crm/setup/practice/connect/",
        connection_views.crm_setup_practice_connect,
        name="crm_setup_practice_connect",
    ),
    path(
        "crm/setup/complete/",
        connection_views.crm_setup_complete,
        name="crm_setup_complete",
    ),
    path(
        "crm/setup/salesforce/",
        connection_views.crm_setup_salesforce,
        name="crm_setup_salesforce",
    ),
    path(
        "crm/setup/salesforce/save/",
        connection_views.crm_setup_salesforce_save,
        name="crm_setup_salesforce_save",
    ),
    path(
        "crm/setup/salesforce/connect/",
        connection_views.crm_setup_salesforce_connect,
        name="crm_setup_salesforce_connect",
    ),
    path(
        "crm/setup/salesforce/connect/submit/",
        connection_views.crm_setup_salesforce_connect_submit,
        name="crm_setup_salesforce_connect_submit",
    ),
    path(
        "crm/setup/hubspot/",
        connection_views.crm_setup_hubspot,
        name="crm_setup_hubspot",
    ),
    path(
        "crm/setup/hubspot/save/",
        connection_views.crm_setup_hubspot_save,
        name="crm_setup_hubspot_save",
    ),
    path(
        "crm/setup/hubspot/connect/",
        connection_views.crm_setup_hubspot_connect,
        name="crm_setup_hubspot_connect",
    ),
    path(
        "crm/setup/hubspot/connect/submit/",
        connection_views.crm_setup_hubspot_connect_submit,
        name="crm_setup_hubspot_connect_submit",
    ),
    path(
        "crm/setup/<str:provider_key>/",
        connection_views.crm_setup_provider,
        name="crm_setup_provider",
    ),
    path("settings/", settings_views.local_settings, name="local_settings"),
    path(
        "settings/storage/",
        settings_views.local_settings_storage,
        name="local_settings_storage",
    ),
    path(
        "settings/crm-app-registrations/salesforce/",
        settings_views.local_settings_salesforce_registration,
        name="local_settings_salesforce_registration",
    ),
    path(
        "settings/crm-app-registrations/salesforce/rotate-secret/",
        settings_views.local_settings_rotate_secret,
        name="local_settings_rotate_secret",
    ),
    path(
        "settings/crm-app-registrations/hubspot/",
        settings_views.local_settings_hubspot_registration,
        name="local_settings_hubspot_registration",
    ),
    path(
        "settings/crm-app-registrations/hubspot/rotate-secret/",
        settings_views.local_settings_rotate_hubspot_secret,
        name="local_settings_rotate_hubspot_secret",
    ),
    path(
        "settings/crm-app-registrations/<str:provider_key>/remove/",
        settings_views.local_settings_remove_registration,
        name="local_settings_remove_registration",
    ),
    path(
        "settings/registrations/<str:provider_key>/start-over/",
        settings_views.registration_start_over,
        name="registration_start_over",
    ),
    path("crm/connect/", connection_views.crm_connect, name="crm_connect"),
    path(
        "crm/connections/<str:connection_id>/reconnect/",
        connection_views.crm_reconnect,
        name="crm_reconnect",
    ),
    path(
        "crm/connections/<str:connection_id>/reconnect/continue/",
        connection_views.crm_reconnect_continue,
        name="crm_reconnect_continue",
    ),
    path(
        "crm/connections/<str:connection_id>/reconnect/abandon/",
        connection_views.crm_reconnect_abandon,
        name="crm_reconnect_abandon",
    ),
    path(
        "crm/oauth/callback/",
        connection_views.crm_oauth_callback,
        name="crm_oauth_callback",
    ),
    path(
        "crm/connections/<str:connection_id>/reclaim/",
        connection_views.crm_reclaim,
        name="crm_reclaim",
    ),
    path(
        "crm/connections/<str:connection_id>/disconnect/",
        connection_views.crm_disconnect,
        name="crm_disconnect",
    ),
    path(
        "crm/connections/<str:connection_id>/remove/",
        connection_views.crm_connection_remove,
        name="crm_connection_remove",
    ),
    path(
        "crm/connections/<str:connection_id>/abandon-uncertain/",
        connection_views.crm_abandon_uncertain_connection,
        name="crm_abandon_uncertain_connection",
    ),
    path(
        "crm/duplicate-journeys/",
        journey_views.crm_duplicate_journey,
        name="crm_duplicate_journey",
    ),
    path(
        "crm/duplicate-journeys/<str:journey_id>/clear/",
        journey_views.crm_duplicate_journey_clear,
        name="crm_duplicate_journey_clear",
    ),
    path(
        "crm/connections/<str:connection_id>/remove/confirm/",
        connection_views.crm_connection_remove_confirm,
        name="crm_connection_remove_confirm",
    ),
    path(
        "crm/connections/<str:connection_id>/remove/confirm/submit/",
        connection_views.crm_connection_remove_with_dependents,
        name="crm_connection_remove_with_dependents",
    ),
    path(
        "crm/duplicate-journeys/<str:journey_id>/abandon/",
        journey_views.crm_duplicate_journey_abandon,
        name="crm_duplicate_journey_abandon",
    ),
    path(
        "sessions/<uuid:session_id>/crm-duplicates/map-record-id/",
        journey_views.crm_duplicate_population_map,
        name="crm_duplicate_population_map",
    ),
    path(
        "sessions/<uuid:session_id>/crm-duplicates/progress/",
        journey_views.crm_duplicate_journey_progress,
        name="crm_duplicate_journey_progress",
    ),
    path(
        "sessions/<uuid:session_id>/crm-duplicates/recover-saved-progress/",
        journey_views.crm_duplicate_reference_acquisition_recovery,
        name="crm_duplicate_reference_acquisition_recovery",
    ),
    path(
        "sessions/<uuid:session_id>/crm-duplicates/review/",
        journey_views.crm_duplicate_journey_review,
        name="crm_duplicate_journey_review",
    ),
    path(
        "sessions/<uuid:session_id>/crm-duplicates/merge/",
        journey_views.crm_duplicate_journey_merge,
        name="crm_duplicate_journey_merge",
    ),
    path(
        "crm/queries/",
        query_views.crm_query,
        name="crm_query",
    ),
    path(
        "crm/queries/<str:query_id>/",
        query_views.crm_query_detail,
        name="crm_query_detail",
    ),
    path("sessions/new/", workflow_views.start_session, name="start_session"),
    path(
        "sessions/<uuid:session_id>/delete/",
        workflow_views.archive,
        name="delete_session",
    ),
    path("sessions/<uuid:session_id>/product/", workflow_views.product, name="product"),
    path("sessions/<uuid:session_id>/upload/", workflow_views.upload, name="upload"),
    path(
        "sessions/<uuid:session_id>/column-mapping/",
        column_mapping_views.column_mapping_session,
        name="column_mapping_session",
    ),
    path(
        "sessions/<uuid:session_id>/column-mapping/<str:plan_id>/",
        column_mapping_views.column_mapping_review,
        name="column_mapping_review",
    ),
    path(
        "sessions/<uuid:session_id>/uploads/<int:source_id>/replace/",
        workflow_views.replace_upload,
        name="replace_upload",
    ),
    path(
        "sessions/<uuid:session_id>/uploads/<int:source_id>/detach/",
        workflow_views.detach_upload,
        name="detach_upload",
    ),
    path(
        "sessions/<uuid:session_id>/configure/",
        workflow_views.configure,
        name="configure",
    ),
    path(
        "sessions/<uuid:session_id>/configure/campaign-lookup/",
        workflow_views.campaign_lookup_proxy,
        name="campaign_lookup",
    ),
    path(
        "sessions/<uuid:session_id>/configure/campaign-resolution/",
        workflow_views.campaign_resolution_pick,
        name="campaign_resolution_pick",
    ),
    path(
        "sessions/<uuid:session_id>/configure/campaign-resolution/clear/",
        workflow_views.campaign_resolution_clear,
        name="campaign_resolution_clear",
    ),
    path(
        "sessions/<uuid:session_id>/workflow/", workflow_views.workflow, name="workflow"
    ),
    path(
        "sessions/<uuid:session_id>/decisions/",
        workflow_views.submit_decision,
        name="submit_decision",
    ),
    path(
        "sessions/<uuid:session_id>/effects/authorize/",
        workflow_views.authorize_effect,
        name="authorize_effect",
    ),
    path(
        "sessions/<uuid:session_id>/effects/resume/",
        workflow_views.resume_effect,
        name="resume_effect",
    ),
    path(
        "sessions/<uuid:session_id>/duplicate-execution/continue/",
        workflow_views.continue_duplicate_execution,
        name="continue_duplicate_execution",
    ),
    path(
        "sessions/<uuid:session_id>/duplicate-execution/finish/",
        workflow_views.finish_duplicate_execution,
        name="finish_duplicate_execution",
    ),
    path(
        "sessions/<uuid:session_id>/duplicate-execution/exceptions/",
        workflow_views.duplicate_execution_exceptions,
        name="duplicate_execution_exceptions",
    ),
    path(
        "sessions/<uuid:session_id>/reviews/",
        workflow_views.start_review,
        name="start_review",
    ),
    path(
        "sessions/<uuid:session_id>/decision-set/",
        workflow_views.create_decision_set,
        name="create_decision_set",
    ),
    path(
        "sessions/<uuid:session_id>/continuations/",
        workflow_views.continue_source,
        name="continue_source",
    ),
    path(
        "sessions/<uuid:session_id>/mutations/<uuid:mutation_id>/retry/",
        workflow_views.retry_mutation,
        name="retry_mutation",
    ),
    path(
        "sessions/<uuid:session_id>/mutations/<uuid:mutation_id>/status/",
        workflow_views.mutation_status,
        name="mutation_status",
    ),
    path(
        "sessions/<uuid:session_id>/mutations/<uuid:mutation_id>/acknowledge/",
        workflow_views.acknowledge_rejection,
        name="acknowledge_rejection",
    ),
    path(
        "sessions/<uuid:session_id>/artifacts/<str:run_id>/<str:artifact_id>/",
        workflow_views.artifact,
        name="artifact",
    ),
    path(
        "sessions/<uuid:session_id>/run-output-package/",
        workflow_views.create_run_output_package,
        name="create_run_output_package",
    ),
    path(
        "sessions/<uuid:session_id>/run-output-packages/<str:package_id>/",
        workflow_views.run_output_package_content,
        name="run_output_package_content",
    ),
    path("pricing/", billing_views.pricing, name="pricing"),
    path("pricing/checkout/", billing_views.checkout, name="checkout"),
    path("pricing/return/", billing_views.payment_return, name="payment_return"),
]
