# Generated by Django 5.2.15 on 2026-07-01 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("raw_list", "Marketing list to import"),
                            ("contacts", "Salesforce Contacts export"),
                            ("accounts", "Salesforce Accounts export"),
                            ("leads", "Salesforce Leads export"),
                            ("users", "Salesforce Users export"),
                            ("territory", "Territory / ownership export"),
                        ],
                        max_length=32,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("stored_path", models.CharField(max_length=1024)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="importer.importsession",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "uploaded_at"],
            },
        ),
    ]
