# Generated by Django 5.2.15 on 2026-07-01 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="woocommerce", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("plan_name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "amount_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending payment"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("wc_order_id", models.IntegerField(blank=True, null=True)),
                (
                    "wc_order_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "payment_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
