# Generated by Django 5.0.2 on 2026-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_api_client_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcefile",
            name="role",
            field=models.CharField(
                choices=[
                    ("raw_list", "Account list"),
                    ("contacts", "Salesforce Contacts export"),
                    ("accounts", "Salesforce Accounts export"),
                    ("leads", "Salesforce Leads export"),
                    ("users", "Salesforce Users export"),
                    ("territory", "Territory / ownership export"),
                    ("company_exclusions", "Company exclusions"),
                    ("industry_mapping", "Industry mapping"),
                    ("dataset", "Dataset"),
                    ("canonical_records", "Canonical CRM records"),
                    ("related_contacts", "Related Contacts"),
                    ("related_leads", "Related Leads"),
                    ("opportunities", "Opportunities"),
                ],
                max_length=64,
            ),
        ),
    ]
