# Generated by Django 5.0.2 on 2026-07-20 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def preserve_one_active_upload_slot(apps, schema_editor):
    """Detach older pre-journal sources without deleting their retained bytes."""
    SourceFile = apps.get_model("importer", "SourceFile")
    duplicates = (
        SourceFile.objects.exclude(upload_mutation_id=None)
        .values("session_id", "role")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    for duplicate in duplicates.iterator():
        rows = SourceFile.objects.filter(
            session_id=duplicate["session_id"],
            role=duplicate["role"],
            upload_mutation_id__isnull=False,
        ).order_by("-uploaded_at", "-id")
        keeper = rows.first()
        rows.exclude(pk=keeper.pk).update(upload_mutation_id=None)

    duplicate_mutations = (
        SourceFile.objects.exclude(upload_mutation_id=None)
        .values("upload_mutation_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    for duplicate in duplicate_mutations.iterator():
        rows = SourceFile.objects.filter(
            upload_mutation_id=duplicate["upload_mutation_id"]
        ).order_by("-uploaded_at", "-id")
        keeper = rows.first()
        rows.exclude(pk=keeper.pk).update(upload_mutation_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0004_alter_sourcefile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="apimutation",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apimutation",
            name="first_submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="apimutation",
            name="form_payload_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="apimutation",
            name="logical_action_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apimutation",
            name="logical_action_identity",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="apimutation",
            name="replacement_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_mutations",
                to="importer.apimutation",
            ),
        ),
        migrations.AddField(
            model_name="importsession",
            name="operator_label",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="importsession",
            name="operator_label_frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="replacement_authorized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="slot_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            preserve_one_active_upload_slot,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="upload_mutation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_source",
                to="importer.apimutation",
            ),
        ),
        migrations.AddConstraint(
            model_name="apimutation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("logical_action_identity", ""), _negated=True),
                fields=(
                    "session",
                    "logical_action_identity",
                    "logical_action_generation",
                ),
                name="unique_api_logical_action_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcefile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("upload_mutation__isnull", False)),
                fields=("session", "role"),
                name="unique_active_api_upload_slot",
            ),
        ),
    ]
