# Generated by Django 5.2.16 on 2026-08-04 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _migrate_options_attempt_map(apps, schema_editor):
    """Lift legacy journal.options['crm_dupe_4a_attempts'] into unique rows."""

    ImportSession = apps.get_model("importer", "ImportSession")
    Claim = apps.get_model("importer", "CrmDuplicateJourneyAttemptClaim")
    intent_keys = (
        "source_mode",
        "connection_id",
        "entity_family",
        "duplicate_execution_maximum",
    )
    for journal in ImportSession.objects.iterator():
        options = dict(journal.options or {})
        attempts = dict(options.get("crm_dupe_4a_attempts") or {})
        if not attempts:
            continue
        for raw_root, raw_entry in attempts.items():
            try:
                root = uuid.UUID(str(raw_root))
            except (ValueError, TypeError, AttributeError):
                continue
            session_id = None
            intent = {}
            if isinstance(raw_entry, str):
                session_id = raw_entry.strip()
            elif isinstance(raw_entry, dict):
                session_id = str(raw_entry.get("session_id") or "").strip()
                raw_intent = raw_entry.get("intent") or {}
                if isinstance(raw_intent, dict):
                    intent = {
                        key: str(raw_intent.get(key) or "").strip()
                        for key in intent_keys
                    }
            if not session_id:
                continue
            try:
                claimed = ImportSession.objects.get(pk=session_id)
            except (ImportSession.DoesNotExist, ValueError, TypeError):
                continue
            if not all(intent.get(key) for key in intent_keys):
                claimed_opts = dict(claimed.options or {})
                intent = {
                    key: str(
                        intent.get(key) or claimed_opts.get(key) or ""
                    ).strip()
                    for key in intent_keys
                }
            if not all(intent.values()):
                continue
            Claim.objects.get_or_create(
                journal_id=journal.pk,
                root_form_instance=root,
                defaults={
                    "claimed_session_id": claimed.pk,
                    "source_mode": intent["source_mode"],
                    "connection_id": intent["connection_id"],
                    "entity_family": intent["entity_family"],
                    "duplicate_execution_maximum": intent[
                        "duplicate_execution_maximum"
                    ],
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0007_sourcefile_detach_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmDuplicateJourneyAttemptClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("root_form_instance", models.UUIDField(db_index=True)),
                ("source_mode", models.CharField(max_length=64)),
                ("connection_id", models.CharField(max_length=160)),
                ("entity_family", models.CharField(max_length=32)),
                ("duplicate_execution_maximum", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimed_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_dupe_4a_claimed_by",
                        to="importer.importsession",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_dupe_4a_attempt_claims",
                        to="importer.importsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("journal", "root_form_instance"),
                        name="unique_crm_dupe_4a_attempt_claim",
                    )
                ],
            },
        ),
        migrations.RunPython(
            _migrate_options_attempt_map,
            migrations.RunPython.noop,
        ),
    ]
